declare const api: {
    getSquareInCircleSide: (radius: number, decimalPlaces?: number) => number;
    guid: () => string;
    newId: () => string;
    getRandomRGBColor: () => import("./main/types").RGBColor;
    getRandomHexColor: () => string;
    getRandomHSLColor: () => import("./main/types").HSLColor;
    getRandomHSLColorWithHue: (h: number) => import("./main/types").HSLColor;
    getRandomHSLColorWithSaturation: (s: number) => import("./main/types").HSLColor;
    getRandomHSLColorWithLightness: (l: number) => import("./main/types").HSLColor;
    getRandomGrayscaleHSLColor: () => import("./main/types").HSLColor;
    getRandomHSLColorWithinRanges: (hueStart?: number, hueEnd?: number, saturationStart?: number, saturationEnd?: number, lightStart?: number, lightEnd?: number) => import("./main/types").HSLColor;
    rgbToHsl: (rgb: import("./main/types").RGBColor, decimalPlaces?: number) => import("./main/types").HSLColor;
    hslToRgb: (hsl: import("./main/types").HSLColor, decimalPlaces?: number) => import("./main/types").RGBColor;
    hslToHex: (hsl: import("./main/types").HSLColor) => string;
    getShiftedHue: (color: import("./main/types").HSLColor, shift?: number) => import("./main/types").HSLColor;
    getShiftedLightness: (color: import("./main/types").HSLColor, shift?: number) => import("./main/types").HSLColor;
    getShiftedSaturation: (color: import("./main/types").HSLColor, shift?: number) => import("./main/types").HSLColor;
    circleMovement: (center: import("./main/types").Vector2, angle: number, radius: number) => import("./main/types").Vector2;
    circleMovementAfterMouse: (mouse: import("./main/types").Vector2, center: import("./main/types").Vector2, radius: number) => import("./main/types").Vector2;
    ellipseMovement: (center: import("./main/types").Vector2, angle: number, radius1: number, radius2: number) => import("./main/types").Vector2;
    sineWaveMovement: (x: number, amplitude: number, frequency: number, phase: number) => import("./main/types").Vector2;
    lissajousCurve: (width: number, height: number, t: number, k: number, n: number, m: number, p: number) => import("./main/types").Vector2;
    equationSystem2: (equation1: import("./main/types").Vector3, equation2: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Vector2 | null;
    equationSystem3: (equation1: import("./main/types").Vector, equation2: import("./main/types").Vector, equation3: import("./main/types").Vector, decimalPlaces?: number) => import("./main/types").Vector3 | null;
    equationSystemN: (equations: import("./main/types").Matrix, decimalPlaces?: number) => import("./main/types").Vector | null;
    v2QuadraticBezierCurve: (t: number, startControlPoint: import("./main/types").Vector2, centerControlPoint: import("./main/types").Vector2, endControlPoint: import("./main/types").Vector2) => import("./main/types").Vector2;
    v3QuadraticBezierCurve: (t: number, startControlPoint: import("./main/types").Vector3, centerControlPoint: import("./main/types").Vector3, endControlPoint: import("./main/types").Vector3) => import("./main/types").Vector3;
    v2CubicBezierCurve: (t: number, startControlPoint: import("./main/types").Vector2, center1ControlPoint: import("./main/types").Vector2, center2ControlPoint: import("./main/types").Vector2, endControlPoint: import("./main/types").Vector2) => import("./main/types").Vector2;
    v3CubicBezierCurve: (t: number, startControlPoint: import("./main/types").Vector3, center1ControlPoint: import("./main/types").Vector3, center2ControlPoint: import("./main/types").Vector3, endControlPoint: import("./main/types").Vector3) => import("./main/types").Vector3;
    stringToNumber: (value: string | number | null | undefined, defaultNumber: number) => number;
    mod: (n: number, m: number) => number;
    convertRange: (x: number, a: number, b: number, c: number, d: number) => number;
    doRangesOverlap: (a: number, b: number, c: number, d: number) => boolean;
    isNumber: (value: any) => boolean;
    getRandom: (min: number, max: number, decimalPlaces?: number) => number;
    getRandomInt: (min: number, max: number) => number;
    getRandomBoolean: () => boolean;
    getRandomItemFromArray: (array: any[]) => any;
    getV2Angle: (v2: import("./main/types").Vector2, decimalPlaces?: number) => number;
    setV2Angle: (v2: import("./main/types").Vector2, newAngleRad: number, decimalPlaces?: number) => import("./main/types").Vector2;
    radiansToDegrees: (radians: number, decimalPlaces?: number) => number;
    degreesToRadians: (degrees: number, decimalPlaces?: number) => number;
    getVNAngleBetween: (vector1: import("./main/types").Vector, vector2: import("./main/types").Vector, decimalPlaces?: number) => number;
    getV2AngleBetween: (vector1: import("./main/types").Vector2, vector2: import("./main/types").Vector2, decimalPlaces?: number) => number;
    getV3AngleBetween: (vector1: import("./main/types").Vector3, vector2: import("./main/types").Vector3, decimalPlaces?: number) => number;
    setDecimalPlaces: (num: number, decimalPlaces?: number | undefined) => number;
    m2ToCSS: (m: import("./main/types").Matrix2) => string;
    m2hToCSS: (m: import("./main/types").Matrix3) => string;
    m2hToCSS3d: (m: import("./main/types").Matrix3) => string;
    m3hToCSS3d: (m: import("./main/types").Matrix4) => string;
    m2Translation: (position: import("./main/types").Vector2, decimalPlaces?: number) => import("./main/types").Matrix2;
    m3Translation: (position: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Matrix3;
    m2TranslationH: (position: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Matrix3;
    m3TranslationH: (position: import("./main/types").Vector4, decimalPlaces?: number) => import("./main/types").Matrix4;
    m2Rotation: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix2;
    m2RotationH: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix3;
    m2RotationAroundPointH: (angleRad: number, transformOrigin: import("./main/types").Vector3, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix3;
    m2RotateAroundPointH: (angleRad: number, transformOrigin: import("./main/types").Vector3, position: import("./main/types").Vector3, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Vector3;
    v2Rotate: (angleRad: number, vector: import("./main/types").Vector2, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Vector2;
    v2RotateH: (angleRad: number, vector: import("./main/types").Vector3, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Vector3;
    m3RotationX: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix3;
    m3RotationXH: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix4;
    v3RotateX: (angleRad: number, vector: import("./main/types").Vector3, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Vector3;
    m3RotationY: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix3;
    m3RotationYH: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix4;
    v3RotateY: (angleRad: number, vector: import("./main/types").Vector3, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Vector3;
    m3RotationZ: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix3;
    m3RotationZH: (angleRad: number, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Matrix4;
    v3RotateZ: (angleRad: number, vector: import("./main/types").Vector3, isClockwise?: boolean, decimalPlaces?: number) => import("./main/types").Vector3;
    m2ScaleAtPointHMatrix: (scaleVector: import("./main/types").Vector3, transformOrigin: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Matrix3;
    m2ScaleAtPointH: (scaleVector: import("./main/types").Vector3, transformOrigin: import("./main/types").Vector3, point: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Vector3;
    m2Scale: (scaleVector: import("./main/types").Vector2) => import("./main/types").Matrix2;
    v2Scale: (scaleVector: import("./main/types").Vector2, vector: import("./main/types").Vector2) => import("./main/types").Vector2;
    m2ScaleH: (scaleVector: import("./main/types").Vector3) => import("./main/types").Matrix3;
    m3Scale: (scaleVector: import("./main/types").Vector3) => import("./main/types").Matrix3;
    m3ScaleH: (scaleVector: import("./main/types").Vector4) => import("./main/types").Matrix4;
    v3Scale: (scaleVector: import("./main/types").Vector3, vector: import("./main/types").Vector3) => import("./main/types").Vector3;
    m2ScaleX: (scale: number) => import("./main/types").Matrix2;
    m2ScaleXH: (scale: number) => import("./main/types").Matrix3;
    m3ScaleX: (scale: number) => import("./main/types").Matrix3;
    m3ScaleXH: (scale: number) => import("./main/types").Matrix4;
    m3ScaleY: (scale: number) => import("./main/types").Matrix3;
    m3ScaleYH: (scale: number) => import("./main/types").Matrix;
    m3ScaleZ: (scale: number) => import("./main/types").Matrix3;
    m3ScaleZH: (scale: number) => import("./main/types").Matrix4;
    m2ScaleY: (scale: number) => import("./main/types").Matrix2;
    m2ScaleYH: (scale: number) => import("./main/types").Matrix3;
    m2ReflectionOrigin: () => import("./main/types").Matrix2;
    m2ReflectionOriginH: () => import("./main/types").Matrix3;
    m3ReflectionOrigin: () => import("./main/types").Matrix3;
    m3ReflectionOriginH: () => import("./main/types").Matrix4;
    m2ReflectionYmX: () => import("./main/types").Matrix2;
    m2ReflectionX: () => import("./main/types").Matrix2;
    m2ReflectionXH: () => import("./main/types").Matrix3;
    m2ReflectionY: () => import("./main/types").Matrix2;
    m2ReflectionYH: () => import("./main/types").Matrix3;
    m3ReflectionYZ: () => import("./main/types").Matrix3;
    m3ReflectionYZH: () => import("./main/types").Matrix4;
    m3ReflectionXZ: () => import("./main/types").Matrix3;
    m3ReflectionXZH: () => import("./main/types").Matrix4;
    m3ReflectionXY: () => import("./main/types").Matrix3;
    m3ReflectionXYH: () => import("./main/types").Matrix4;
    m2ShearingY: (factor: number) => import("./main/types").Matrix2;
    m2ShearingX: (factor: number) => import("./main/types").Matrix2;
    mSum: (matrix1: import("./main/types").Matrix, matrix2: import("./main/types").Matrix, decimalPlaces?: number) => import("./main/types").Matrix;
    m2Sum: (matrix1: import("./main/types").Matrix2, matrix2: import("./main/types").Matrix2, decimalPlaces?: number) => import("./main/types").Matrix2;
    m3Sum: (matrix1: import("./main/types").Matrix3, matrix2: import("./main/types").Matrix3, decimalPlaces?: number) => import("./main/types").Matrix3;
    mSub: (matrix1: import("./main/types").Matrix, matrix2: import("./main/types").Matrix, decimalPlaces?: number) => import("./main/types").Matrix;
    m2Sub: (matrix1: import("./main/types").Matrix2, matrix2: import("./main/types").Matrix2, decimalPlaces?: number) => import("./main/types").Matrix2;
    m3Sub: (matrix1: import("./main/types").Matrix3, matrix2: import("./main/types").Matrix3, decimalPlaces?: number) => import("./main/types").Matrix3;
    mMulScalar: (m: import("./main/types").Matrix, scalar: number, decimalPlaces?: number) => import("./main/types").Matrix;
    m2MulScalar: (m2: import("./main/types").Matrix2, scalar: number, decimalPlaces?: number) => import("./main/types").Matrix2;
    m3MulScalar: (m3: import("./main/types").Matrix3, scalar: number, decimalPlaces?: number) => import("./main/types").Matrix3;
    mDivideScalar: (m: import("./main/types").Matrix, scalar: number, decimalPlaces?: number) => import("./main/types").Matrix;
    m2DivideScalar: (m2: import("./main/types").Matrix2, scalar: number, decimalPlaces?: number) => import("./main/types").Matrix2;
    m3DivideScalar: (m3: import("./main/types").Matrix3, scalar: number, decimalPlaces?: number) => import("./main/types").Matrix3;
    mTranspose: (m: import("./main/types").Matrix) => import("./main/types").Matrix;
    m2Transpose: (m2: import("./main/types").Matrix2) => import("./main/types").Matrix;
    m3Transpose: (m3: import("./main/types").Matrix3) => import("./main/types").Matrix;
    mReset: (m: import("./main/types").Matrix, defaultValue?: number) => import("./main/types").Matrix;
    m2Reset: (m2: import("./main/types").Matrix2, defaultValue?: number) => import("./main/types").Matrix2;
    m3Reset: (m3: import("./main/types").Matrix3, defaultValue?: number) => import("./main/types").Matrix3;
    m2x2: (defaultValue?: number) => import("./main/types").Matrix2;
    m3x3: (defaultValue?: number) => import("./main/types").Matrix3;
    m4x4: (defaultValue?: number) => import("./main/types").Matrix4;
    mNxM: (N: number, M: number, defaultValue?: number) => import("./main/types").Matrix;
    identity2: () => import("./main/types").Matrix2;
    identity3: () => import("./main/types").Matrix3;
    identity4: () => import("./main/types").Matrix4;
    identityN: (N: number) => import("./main/types").Matrix;
    mDeepCopy: (m: import("./main/types").Matrix) => import("./main/types").Matrix;
    m2DeepCopy: (m2: import("./main/types").Matrix2) => import("./main/types").Matrix2;
    m3DeepCopy: (m3: import("./main/types").Matrix3) => import("./main/types").Matrix3;
    mAppendCol: (m: import("./main/types").Matrix, col: import("./main/types").Vector) => import("./main/types").Matrix;
    mPrependCol: (m: import("./main/types").Matrix, col: import("./main/types").Vector) => import("./main/types").Matrix;
    mAppendRow: (m: import("./main/types").Matrix, row: import("./main/types").Vector) => import("./main/types").Matrix;
    m2AppendRow: (m2: import("./main/types").Matrix2, row: import("./main/types").Vector2) => import("./main/types").Matrix2;
    m3AppendRow: (m3: import("./main/types").Matrix3, row: import("./main/types").Vector3) => import("./main/types").Matrix3;
    mPrependRow: (m: import("./main/types").Matrix, row: import("./main/types").Vector) => import("./main/types").Matrix;
    m2PrependRow: (m2: import("./main/types").Matrix2, row: import("./main/types").Vector2) => import("./main/types").Matrix2;
    m3PrependRow: (m3: import("./main/types").Matrix3, row: import("./main/types").Vector3) => import("./main/types").Matrix3;
    mDelLastRow: (m: import("./main/types").Matrix) => import("./main/types").Matrix;
    mDelFirstRow: (m: import("./main/types").Matrix) => import("./main/types").Matrix;
    mDelLastColumn: (m: import("./main/types").Matrix) => import("./main/types").Matrix;
    mDelFirstColumn: (m: import("./main/types").Matrix) => import("./main/types").Matrix;
    mGetFirstColumn: (m: import("./main/types").Matrix) => import("./main/types").Vector;
    mGetLastColumn: (m: import("./main/types").Matrix) => import("./main/types").Vector;
    mGetColumn: (m: import("./main/types").Matrix, colIndex: number) => import("./main/types").Vector;
    mMul: (matrix1: import("./main/types").Matrix, matrix2: import("./main/types").Matrix, decimalPlaces?: number) => import("./main/types").Matrix;
    mMulVector: (matrix: import("./main/types").Matrix, vector: import("./main/types").Vector, decimalPlaces?: number) => import("./main/types").Vector;
    mEqual: (matrix1: import("./main/types").Matrix, matrix2: import("./main/types").Matrix) => boolean;
    mMinor: (m: import("./main/types").Matrix, row: number, col: number) => number;
    mDeterminant: (matrix: import("./main/types").Matrix) => number;
    m2Determinant: (m2: import("./main/types").Matrix2) => number;
    m3Determinant: (m3: import("./main/types").Matrix3) => number;
    m2Adjugate: (m2: import("./main/types").Matrix2) => import("./main/types").Matrix2 | null;
    m3Adjugate: (m3: import("./main/types").Matrix3) => import("./main/types").Matrix3 | null;
    mAdjugate: (m: import("./main/types").Matrix) => import("./main/types").Matrix | null;
    isSingularMatrix: (m: import("./main/types").Matrix) => boolean;
    m2Inverse: (m2: import("./main/types").Matrix2, decimalPlaces?: number) => import("./main/types").Matrix2 | null;
    m3Inverse: (m3: import("./main/types").Matrix3, decimalPlaces?: number) => import("./main/types").Matrix3 | null;
    mInverse: (m: import("./main/types").Matrix, decimalPlaces?: number) => import("./main/types").Matrix | null;
    vSum: (vector1: import("./main/types").Vector, vector2: import("./main/types").Vector, decimalPlaces?: number) => import("./main/types").Vector;
    v2Sum: (vector1: import("./main/types").Vector2, vector2: import("./main/types").Vector2, decimalPlaces?: number) => import("./main/types").Vector2;
    v3Sum: (vector1: import("./main/types").Vector3, vector2: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Vector3;
    vSub: (vector1: import("./main/types").Vector, vector2: import("./main/types").Vector, decimalPlaces?: number) => import("./main/types").Vector;
    v2Sub: (vector1: import("./main/types").Vector2, vector2: import("./main/types").Vector2, decimalPlaces?: number) => import("./main/types").Vector2;
    v3Sub: (vector1: import("./main/types").Vector3, vector2: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Vector3;
    vMulScalar: (v: import("./main/types").Vector, scalar: number, decimalPlaces?: number) => import("./main/types").Vector;
    v2MulScalar: (v2: import("./main/types").Vector2, scalar: number, decimalPlaces?: number) => import("./main/types").Vector2;
    v3MulScalar: (v3: import("./main/types").Vector3, scalar: number, decimalPlaces?: number) => import("./main/types").Vector3;
    vDivideScalar: (v: import("./main/types").Vector, scalar: number, decimalPlaces?: number) => import("./main/types").Vector;
    v2DivideScalar: (v2: import("./main/types").Vector2, scalar: number, decimalPlaces?: number) => import("./main/types").Vector2;
    v3DivideScalar: (v3: import("./main/types").Vector3, scalar: number, decimalPlaces?: number) => import("./main/types").Vector3;
    vLength: (vector: import("./main/types").Vector, decimalPlaces?: number) => number;
    v2Length: (vector: import("./main/types").Vector2, decimalPlaces?: number) => number;
    v3Length: (vector: import("./main/types").Vector3, decimalPlaces?: number) => number;
    v2SetLength: (v2: import("./main/types").Vector2, newLength: number, decimalPlaces?: number) => import("./main/types").Vector2;
    vDistance: (vector1: import("./main/types").Vector, vector2: import("./main/types").Vector, decimalPlaces?: number) => number;
    v2Distance: (vector1: import("./main/types").Vector2, vector2: import("./main/types").Vector2, decimalPlaces?: number) => number;
    v3Distance: (vector1: import("./main/types").Vector3, vector2: import("./main/types").Vector3, decimalPlaces?: number) => number;
    vNormalize: (v: import("./main/types").Vector, decimalPlaces?: number) => import("./main/types").Vector;
    v2Normalize: (v2: import("./main/types").Vector2, decimalPlaces?: number) => import("./main/types").Vector2;
    v3Normalize: (v3: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Vector3;
    vDotProduct: (vector1: import("./main/types").Vector, vector2: import("./main/types").Vector, decimalPlaces?: number) => number;
    v2DotProduct: (vector1: import("./main/types").Vector2, vector2: import("./main/types").Vector2, decimalPlaces?: number) => number;
    v3DotProduct: (vector1: import("./main/types").Vector3, vector2: import("./main/types").Vector3, decimalPlaces?: number) => number;
    v3CrossProduct: (vector1: import("./main/types").Vector3, vector2: import("./main/types").Vector3, decimalPlaces?: number) => import("./main/types").Vector3;
    v2: (defaultValue?: number) => import("./main/types").Vector2;
    v3: (defaultValue?: number) => import("./main/types").Vector3;
    v4: (defaultValue?: number) => import("./main/types").Vector4;
    vN: (N: number, defaultValue?: number) => import("./main/types").Vector;
    v2FromPolarCoords: (distance: number, angleRad: number) => import("./main/types").Vector2;
    vEqual: (vector1: import("./main/types").Vector, vector2: import("./main/types").Vector) => boolean;
};
declare global {
    interface Window {
        mzMath: typeof api;
    }
}
export * from './main/vector';
export * from './main/matrix';
export * from './main/matrix-transformations';
export * from './main/format';
export * from './main/angle';
export * from './main/random';
export * from './main/other';
export * from './main/convert';
export * from './main/bezier-curve';
export * from './main/equations';
export * from './main/path-movement';
export * from './main/color';
export * from './main/physics';
export * from './main/id';
export * from './main/shapes';
