import { IVector2, IVector3 } from './interfaces';
export declare const v2Sum: (...vectors: IVector2[]) => IVector2;
export declare const v3Sum: (...vectors: IVector3[]) => IVector3;
export declare const v2Sub: (...vectors: IVector2[]) => IVector2;
export declare const v3Sub: (...vectors: IVector3[]) => IVector3;
export declare const v2MulScalar: (v2: IVector2, scalar: number, decimalPlaces?: number) => IVector2;
export declare const v3MulScalar: (v3: IVector3, scalar: number, decimalPlaces?: number) => IVector3;
export declare const v2Length: (vector: IVector2, decimalPlaces?: number) => number;
export declare const v3Length: (vector: IVector3, decimalPlaces?: number) => number;
export declare const v2SetLength: (v2: IVector2, newLength: number, decimalPlaces?: number) => IVector2;
export declare const v2Normalize: (v2: IVector2, decimalPlaces?: number) => IVector2;
export declare const v3Normalize: (v3: IVector3, decimalPlaces?: number) => IVector3;
